### ISSUE TITLE
Hubot can list, but can't create

### ISSUE THREAD

**Issue by dylanh724** [hubot-scripts/hubot-trello#8] opened 2016-03-18 07:53 UTC
Any suggestions on this?

https://i.imgur.com/G4ukLoj.png

**Comment by syntax922** [comment] 2016-03-18 19:29
Do you get any responses in hubot's log? Have you confirmed connection to Trello? (try reading a list that you know exists and has cards in it).

**Comment by dylanh724** [comment] 2016-03-20 12:05
The picture I posted answers your 2nd question, but I figured out the answer:

The readme says to get the ID from the URL, however, that's incorrect:

The ID is obtained from adding ".json" to the URL shown in the readme, then obtaining the ID from the very top of the json file. Suddenly it works~

**Comment by syntax922** [comment] 2016-03-21 18:35
@dylanh724 Opening another issue (Issue #9) for the same one won't help. Let's continue working here. You said that this is now working but you've opened another issue with the same commit saying it's not.

Unfortunately your image does not answer my question about confirming a connection to Trello. Are you able to list cards from a list that already exists? the command "Trello new "_list name_" _description_ is confirmed working in this commit.

**Comment by dylanh724** [comment] 2016-03-22 01:56
Oh sorry, I thought that screen was updated where it shows the list returning. Yes, both work now, but with quirks. My other post I renamed to "How can I add a new LIST?". I'm still newish to Trello and I got the keywords wrong.

I can view a list
I can add a CARD to an EXISTING list
**I cannot add a new list** >> https://github.com/hubot-scripts/hubot-trello/issues/9

**Comment by syntax922** [comment] 2016-03-22 17:44
AHHH-HA! Excellent! Then I might suggest we maybe close this issue (since it doesn't seem to be outstanding, but if it is let's look deeper into it). 

I will post something else on the other issue that is relevant there!

**Comment by codeimpossible** [comment] 2016-05-06 03:35
Closing since create list PR was merged.

**Closed as completed by codeimpossible** 2016-05-06 03:35 UTC
